# Generated by Django 3.1.5 on 2021-01-09 20:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Сфера деятельности')),
            ],
            options={
                'verbose_name': 'Сфера деятельности',
                'verbose_name_plural': 'Сфера деятельности',
                'ordering': ('id', 'name'),
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Название компании')),
                ('opisanie', models.CharField(max_length=255, verbose_name='Описание')),
                ('pochta', models.CharField(max_length=60, verbose_name='E-mail')),
                ('telephon', models.CharField(max_length=11, verbose_name='Номер телефона')),
                ('fio', models.CharField(max_length=255, verbose_name='ФИО представителя')),
                ('login', models.CharField(max_length=60, verbose_name='Логин')),
                ('password', models.CharField(max_length=60, verbose_name='Пароль')),
            ],
            options={
                'verbose_name': 'Компания',
                'verbose_name_plural': 'Компания',
                'ordering': ('id', 'name', 'opisanie', 'pochta', 'telephon', 'fio', 'login', 'password', 'id_role'),
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Название курса')),
                ('opisanie', models.CharField(max_length=255, verbose_name='Описание')),
                ('dlitelnost', models.CharField(max_length=255, verbose_name='Длительность')),
                ('id_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.category', verbose_name='ID сферы деятельности')),
                ('id_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.company', verbose_name='ID компании')),
            ],
            options={
                'verbose_name': 'Курсы',
                'verbose_name_plural': 'Курсы',
                'ordering': ('id', 'name', 'opisanie', 'dlitelnost', 'id_category', 'id_company'),
            },
        ),
        migrations.CreateModel(
            name='Polzovateli',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fio', models.CharField(max_length=255, verbose_name='ФИО пользователя')),
                ('pochta', models.CharField(max_length=60, verbose_name='E-mail')),
                ('login', models.CharField(max_length=60, verbose_name='Логин')),
                ('password', models.CharField(max_length=60, verbose_name='Пароль')),
            ],
            options={
                'verbose_name': 'Пользователи',
                'verbose_name_plural': 'Пользователи',
                'ordering': ('id', 'fio', 'pochta', 'login', 'password', 'id_role'),
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=60, verbose_name='Наименование роли')),
            ],
            options={
                'verbose_name': 'Роли',
                'verbose_name_plural': 'Роли',
                'ordering': ('id', 'name'),
            },
        ),
        migrations.CreateModel(
            name='Vid',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Вид работы')),
            ],
            options={
                'verbose_name': 'Вид работы',
                'verbose_name_plural': 'Вид работы',
                'ordering': ('id', 'name'),
            },
        ),
        migrations.CreateModel(
            name='Zapis',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.course', verbose_name='ID курса')),
                ('id_polzovatel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.polzovateli', verbose_name='ID пользователя')),
            ],
            options={
                'verbose_name': 'Запись на курс',
                'verbose_name_plural': 'Запись на курс',
                'ordering': ('id', 'id_polzovatel', 'id_course'),
            },
        ),
        migrations.CreateModel(
            name='Rabota',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Название вакансии')),
                ('opisanie', models.CharField(max_length=255, verbose_name='Описание')),
                ('trebovanie', models.CharField(max_length=255, verbose_name='Требования')),
                ('uslovia', models.CharField(max_length=255, verbose_name='Условия')),
                ('obyazannosti', models.CharField(max_length=255, verbose_name='Обязанности')),
                ('id_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.category', verbose_name='ID сферы деятельности')),
                ('id_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.company', verbose_name='ID компании')),
                ('id_vida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.vid', verbose_name='ID вида работы')),
            ],
            options={
                'verbose_name': 'Работа',
                'verbose_name_plural': 'Работа',
                'ordering': ('id', 'name', 'opisanie', 'trebovanie', 'uslovia', 'obyazannosti', 'id_category', 'id_vida', 'id_company'),
            },
        ),
        migrations.AddField(
            model_name='polzovateli',
            name='id_role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.role', verbose_name='ID Роли'),
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Заголовок новости')),
                ('opisanie', models.CharField(max_length=255, verbose_name='Описание')),
                ('date', models.DateTimeField(max_length=15, verbose_name='Дата написания статьи')),
                ('status', models.CharField(choices=[('d', 'Draft'), ('p', 'Published'), ('w', 'Withdrawn')], max_length=1)),
                ('id_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.category', verbose_name='ID сферы деятельности')),
                ('id_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.company', verbose_name='ID компании')),
            ],
            options={
                'verbose_name': 'Новости',
                'verbose_name_plural': 'Новости',
                'ordering': ('id', 'name', 'opisanie', 'date', 'id_category', 'id_company'),
            },
        ),
        migrations.CreateModel(
            name='Meropriyatia',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Название мероприятия')),
                ('date', models.DateTimeField(max_length=15, verbose_name='Дата проведения мероприятия')),
                ('id_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.company', verbose_name='ID компании')),
            ],
            options={
                'verbose_name': 'Мероприятия',
                'verbose_name_plural': 'Мероприятия',
                'ordering': ('id', 'name', 'date', 'id_company'),
            },
        ),
        migrations.AddField(
            model_name='company',
            name='id_role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.role', verbose_name='ID Роли'),
        ),
    ]
