# Generated by Django 3.1.5 on 2021-01-09 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='status',
        ),
    ]
