# Generated by Django 3.1.5 on 2021-01-10 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_news_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='status',
            field=models.CharField(default='', max_length=1, verbose_name='Статус'),
        ),
    ]
