# Generated by Django 3.1.5 on 2021-07-05 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210110_1733'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ('id', 'name', 'opisanie', 'date', 'id_category', 'id_company', 'status'), 'verbose_name': 'Новости', 'verbose_name_plural': 'Новости'},
        ),
    ]
