# Generated by Django 3.1.5 on 2021-07-05 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20210705_2237'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'ordering': ('id', 'name', 'opisanie', 'pochta', 'telephon', 'fio', 'login', 'password'), 'verbose_name': 'Компания', 'verbose_name_plural': 'Компания'},
        ),
        migrations.RemoveField(
            model_name='company',
            name='id_role',
        ),
    ]
